### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by umar10001000** [VivekPa/AlphaAI#27]
I'm having some issues, getting these errors:

C:\Windows\System32> C:\Users\kanzl\Downloads\AIAlpha-master\AIAlpha-master\run.py install
Using TensorFlow backend.
Creating tick bars...
Reading data in batches of 20000000
Traceback (most recent call last):
  File "C:\Users\kanzl\Downloads\AIAlpha-master\AIAlpha-master\run.py", line 14, in <module>
    base.batch_run()
  File "C:\Users\kanzl\Downloads\AIAlpha-master\AIAlpha-master\data_processor\base_bars.py", line 23, in batch_run
    for batch in pd.read_csv(self.file_path, chunksize=self.batch_size, index_col=0):
  File "C:\Users\kanzl\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\kanzl\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\kanzl\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Users\kanzl\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\kanzl\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File sample_data/raw_data/price_vol.csv does not exist: 'sample_data/raw_data/price_vol.csv'

If you could help I would appreciate

**Comment by bluusun** [comment]
I have a diff file that is missing :( 

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed_data/sample_data/processed_data/autoencoder_data/train_x.csv'

**Comment by justin13601** [comment]
Me too...

**Comment by saookami** [comment]
Did somebody resolve it ?

**Comment by saookami** [comment]
turn data_processing.py Class
line 95-100
to
            train_x.to_csv(f'{csv_path}/train_x.csv')
            train_y.to_csv(f'{csv_path}/train_y.csv', header=['y_values'])
            test_x.to_csv(f'{csv_path}/test_x.csv')
            test_y.to_csv(f'{csv_path}/test_y.csv', header=['y_values'])
            fulldata.to_csv(f'{csv_path}/full_x.csv')
            y_values.to_csv(f'{csv_path}/full_y.csv', header=['y_values'])

**Comment by ahmedyounis** [comment]
@saookami is right. that worked. 

Too bad we cant make a PR for this. Is the author of this repo still maintaining it?
